// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go

// Package mock_client is a generated GoMock package.
package client

import (
	reflect "reflect"

	model "github.com/adinandradrs/cezbek-engine/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockTransactionProvider is a mock of TransactionProvider interface.
type MockTransactionProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionProviderMockRecorder
}

// MockTransactionProviderMockRecorder is the mock recorder for MockTransactionProvider.
type MockTransactionProviderMockRecorder struct {
	mock *MockTransactionProvider
}

// NewMockTransactionProvider creates a new mock instance.
func NewMockTransactionProvider(ctrl *gomock.Controller) *MockTransactionProvider {
	mock := &MockTransactionProvider{ctrl: ctrl}
	mock.recorder = &MockTransactionProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionProvider) EXPECT() *MockTransactionProviderMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTransactionProvider) Add(inp *model.TransactionRequest) (*model.TransactionResponse, *model.BusinessError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", inp)
	ret0, _ := ret[0].(*model.TransactionResponse)
	ret1, _ := ret[1].(*model.BusinessError)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockTransactionProviderMockRecorder) Add(inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTransactionProvider)(nil).Add), inp)
}

// Tier mocks base method.
func (m *MockTransactionProvider) Tier(inp *model.SessionRequest) (*model.TransactionTierResponse, *model.BusinessError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tier", inp)
	ret0, _ := ret[0].(*model.TransactionTierResponse)
	ret1, _ := ret[1].(*model.BusinessError)
	return ret0, ret1
}

// Tier indicates an expected call of Tier.
func (mr *MockTransactionProviderMockRecorder) Tier(inp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tier", reflect.TypeOf((*MockTransactionProvider)(nil).Tier), inp)
}
