// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Kezbek Developer",
            "url": "https://kezbek.id",
            "email": "developer@kezbek.id"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/partner/v1/transactions": {
            "get": {
                "description": "API to search transaction by partner",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Partner APIs"
                ],
                "summary": "API Transaction Search",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Your Token to Access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "EBIZKEZBEK",
                            "B2BCLIENT"
                        ],
                        "type": "string",
                        "description": "Client Channel",
                        "name": "x-client-channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "android 10",
                        "description": "Client OS or Browser Agent",
                        "name": "x-client-os",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Device ID",
                        "name": "x-client-device",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Client Platform Version",
                        "name": "x-client-version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Original Timestamp in UNIX format (EPOCH)",
                        "name": "x-client-timestamp",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "example": 5,
                        "name": "limit",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "example": 0,
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "text_search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PartnerTransactionSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    }
                }
            }
        },
        "/partner/v1/transactions/{id}": {
            "get": {
                "description": "API to view detail transaction by partner",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Transaction Partner APIs"
                ],
                "summary": "API Transaction Detail",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Your Token to Access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "EBIZKEZBEK",
                            "B2BCLIENT"
                        ],
                        "type": "string",
                        "description": "Client Channel",
                        "name": "x-client-channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "android 10",
                        "description": "Client OS or Browser Agent",
                        "name": "x-client-os",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Device ID",
                        "name": "x-client-device",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Client Platform Version",
                        "name": "x-client-version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Original Timestamp in UNIX format (EPOCH)",
                        "name": "x-client-timestamp",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "Transaction ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.PartnerTransactionProjection"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Ping the status of server, should be respond fastly.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Default APIs"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/authorization/b2b": {
            "post": {
                "description": "API to authorize B2B officer account",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authorization APIs"
                ],
                "summary": "API B2B Authorization",
                "parameters": [
                    {
                        "enum": [
                            "EBIZKEZBEK",
                            "B2BCLIENT"
                        ],
                        "type": "string",
                        "description": "Client Channel",
                        "name": "x-client-channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "android 10",
                        "description": "Client OS or Browser Agent",
                        "name": "x-client-os",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Device ID",
                        "name": "x-client-device",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Client Platform Version",
                        "name": "x-client-version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Original Timestamp in UNIX format (EPOCH)",
                        "name": "x-client-timestamp",
                        "in": "header"
                    },
                    {
                        "description": "B2B Officer Authentication Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OfficerAuthenticationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.OfficerAuthenticationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    }
                }
            }
        },
        "/v1/authorization/client": {
            "post": {
                "description": "API to authorize client's signature and code",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authorization APIs"
                ],
                "summary": "API Client Authorization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client signature using HMAC SHA256, signature formula is \u003cb\u003eHEX(HMAC(SHA256(UPPER(HTTP-METHOD):UPPER(CODE):UNIX-EPOCH:UPPER(API-KEY))))\u003c/b\u003e",
                        "name": "x-client-signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client API Key",
                        "name": "x-api-key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "EBIZKEZBEK",
                            "B2BCLIENT"
                        ],
                        "type": "string",
                        "description": "Client Channel",
                        "name": "x-client-channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "android 10",
                        "description": "Client OS or Browser Agent",
                        "name": "x-client-os",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Device ID",
                        "name": "x-client-device",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Client Platform Version",
                        "name": "x-client-version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Original Timestamp in UNIX format (EPOCH)",
                        "name": "x-client-timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Client Authentication Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ClientAuthenticationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ClientAuthenticationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    }
                }
            }
        },
        "/v1/authorization/otp": {
            "post": {
                "description": "API to validate B2B officer account OTP",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Authorization APIs"
                ],
                "summary": "API B2B OTP Validation",
                "parameters": [
                    {
                        "enum": [
                            "EBIZKEZBEK",
                            "B2BCLIENT"
                        ],
                        "type": "string",
                        "description": "Client Channel",
                        "name": "x-client-channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "android 10",
                        "description": "Client OS or Browser Agent",
                        "name": "x-client-os",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Device ID",
                        "name": "x-client-device",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Client Platform Version",
                        "name": "x-client-version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Original Timestamp in UNIX format (EPOCH)",
                        "name": "x-client-timestamp",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Client Transaction ID",
                        "name": "x-client-trxid",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "B2B Officer Authentication Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OfficerValidationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.OfficerValidationResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    }
                }
            }
        },
        "/v1/cashbacks": {
            "post": {
                "description": "API to apply cashback on client's transaction",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Client Cashback APIs"
                ],
                "summary": "API Apply Cashback",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Your Token to Access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "EBIZKEZBEK",
                            "B2BCLIENT"
                        ],
                        "type": "string",
                        "description": "Client Channel",
                        "name": "x-client-channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "android 10",
                        "description": "Client OS or Browser Agent",
                        "name": "x-client-os",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Device ID",
                        "name": "x-client-device",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Client Platform Version",
                        "name": "x-client-version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Original Timestamp in UNIX format (EPOCH)",
                        "name": "x-client-timestamp",
                        "in": "header"
                    },
                    {
                        "description": "Transaction Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.TransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    }
                }
            }
        },
        "/v1/cashbacks/{msisdn}": {
            "get": {
                "description": "API to retrieve tier information",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Client Cashback APIs"
                ],
                "summary": "API Tier Information",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Your Token to Access",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "enum": [
                            "EBIZKEZBEK",
                            "B2BCLIENT"
                        ],
                        "type": "string",
                        "description": "Client Channel",
                        "name": "x-client-channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "android 10",
                        "description": "Client OS or Browser Agent",
                        "name": "x-client-os",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Device ID",
                        "name": "x-client-device",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Client Platform Version",
                        "name": "x-client-version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Original Timestamp in UNIX format (EPOCH)",
                        "name": "x-client-timestamp",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "Customer MSISDN",
                        "name": "msisdn",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TransactionTierResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    }
                }
            }
        },
        "/v1/partners": {
            "post": {
                "description": "API to register a new B2B Partner data as user and client",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Partner Management APIs"
                ],
                "summary": "API Add Partner",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer",
                        "description": "Your Token to Access",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "enum": [
                            "EBIZKEZBEK",
                            "B2BCLIENT"
                        ],
                        "type": "string",
                        "description": "Client Channel",
                        "name": "x-client-channel",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "android 10",
                        "description": "Client OS or Browser Agent",
                        "name": "x-client-os",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Device ID",
                        "name": "x-client-device",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1.0.0",
                        "description": "Client Platform Version",
                        "name": "x-client-version",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Client Original Timestamp in UNIX format (EPOCH)",
                        "name": "x-client-timestamp",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "PT. Lajada Piranti Commerce",
                        "description": "Partner Corporate",
                        "name": "partner",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "LAJADA",
                        "description": "Partner Code",
                        "name": "code",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "kezbek.support@lajada.net",
                        "description": "Partner Email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "628123456789",
                        "description": "MSISDN",
                        "name": "msisdn",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "John Doe",
                        "description": "Partner Officer",
                        "name": "officer",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "Bintaro Exchange Mall Blok A1",
                        "description": "Office Address",
                        "name": "address",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Logo",
                        "name": "logo",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/model.Meta"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ClientAuthenticationRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "LAJADA"
                }
            }
        },
        "model.ClientAuthenticationResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "**secret**"
                },
                "code": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "expired": {
                    "type": "integer",
                    "example": 11234823643
                },
                "id": {
                    "type": "integer"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "**secret**"
                },
                "token": {
                    "type": "string",
                    "example": "**secret**"
                }
            }
        },
        "model.Meta": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.OfficerAuthenticationRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john.doe@lajada.id"
                }
            }
        },
        "model.OfficerAuthenticationResponse": {
            "type": "object",
            "properties": {
                "remaining_seconds": {
                    "type": "number"
                },
                "transaction_id": {
                    "type": "string",
                    "example": "TRX0012345678"
                },
                "transaction_timestamp": {
                    "type": "integer",
                    "example": 11285736234
                }
            }
        },
        "model.OfficerValidationRequest": {
            "type": "object",
            "required": [
                "otp"
            ],
            "properties": {
                "otp": {
                    "type": "string",
                    "example": "123456"
                }
            }
        },
        "model.OfficerValidationResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "**secret**"
                },
                "code": {
                    "type": "string",
                    "example": "CORPCODE_A"
                },
                "company": {
                    "type": "string",
                    "example": "Kezbek Indonesia Ltd"
                },
                "email": {
                    "type": "string",
                    "example": "john.doe@email.net"
                },
                "expired": {
                    "type": "integer",
                    "example": 11234823643
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "msisdn": {
                    "type": "string",
                    "example": "628118770510"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "**secret**"
                },
                "token": {
                    "type": "string",
                    "example": "**secret**"
                },
                "url_logo": {
                    "type": "string",
                    "example": "https://cdn-something.com/bucket/file.png"
                }
            }
        },
        "model.PartnerTransactionProjection": {
            "type": "object",
            "properties": {
                "cashback": {
                    "type": "number",
                    "example": 2500
                },
                "email": {
                    "type": "string",
                    "example": "john.doe@email.net"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "msisdn": {
                    "type": "string",
                    "example": "628118770510"
                },
                "qty": {
                    "type": "integer",
                    "example": 2
                },
                "reward": {
                    "type": "number",
                    "example": 13000
                },
                "transaction": {
                    "type": "number",
                    "example": 250000
                },
                "wallet_code": {
                    "type": "string",
                    "example": "LSAJA"
                }
            }
        },
        "model.PartnerTransactionSearchResponse": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 10
                },
                "sort": {
                    "type": "string",
                    "example": "ASC"
                },
                "sort_by": {
                    "type": "string",
                    "example": "id"
                },
                "total_elements": {
                    "type": "integer",
                    "example": 100
                },
                "total_pages": {
                    "type": "integer",
                    "example": 10
                },
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PartnerTransactionProjection"
                    }
                }
            }
        },
        "model.TransactionRequest": {
            "type": "object",
            "required": [
                "amount",
                "msisdn",
                "quantity"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "example": 750000
                },
                "email": {
                    "type": "string",
                    "example": "john.doe@gmailxyz.com"
                },
                "merchant_code": {
                    "type": "string",
                    "example": "LSAJA,GPAID,JOSVO"
                },
                "msisdn": {
                    "type": "string",
                    "example": "62812345678"
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                },
                "transaction_reference": {
                    "type": "string",
                    "example": "INV/001/002"
                }
            }
        },
        "model.TransactionResponse": {
            "type": "object",
            "properties": {
                "transaction_id": {
                    "type": "string",
                    "example": "TRX0012345678"
                },
                "transaction_timestamp": {
                    "type": "integer",
                    "example": 11285736234
                }
            }
        },
        "model.TransactionTierResponse": {
            "type": "object",
            "properties": {
                "date_expired": {
                    "type": "string",
                    "example": "2022-01-01"
                },
                "recurring": {
                    "type": "integer",
                    "example": 3
                },
                "tier": {
                    "type": "string",
                    "example": "GOLD"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0-Beta",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Kezbek - Cashback Engine Sandbox",
	Description:      "This Cashback Engine Sandbox is only used for test and development purpose. To explore and serve all Kezbek operational APIs as a live data. It is not intended for production usage.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
