basePath: /api
definitions:
  model.ClientAuthenticationRequest:
    properties:
      code:
        example: LAJADA
        type: string
    required:
    - code
    type: object
  model.OfficerAuthenticationRequest:
    properties:
      email:
        example: john.doe@lajada.id
        type: string
    type: object
  model.OfficerValidationRequest:
    properties:
      otp:
        example: "123456"
        type: string
    required:
    - otp
    type: object
  model.TransactionRequest:
    properties:
      amount:
        example: 750000
        type: number
      email:
        example: john.doe@gmailxyz.com
        type: string
      merchant_code:
        example: LSAJA,GPAID,JOSVO
        type: string
      msisdn:
        example: "62812345678"
        type: string
      quantity:
        example: 2
        type: integer
      transaction_reference:
        example: INV001-GOFOOD-ABC
        type: string
    required:
    - amount
    - msisdn
    - quantity
    type: object
info:
  contact:
    email: developer@kezbek.id
    name: Kezbek Developer
    url: https://kezbek.id
  description: This Cashback Engine Sandbox is only used for test and development
    purpose. To explore and serve all Kezbek operational APIs as a live data. It is
    not intended for production usage.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Kezbek - Cashback Engine Sandbox
  version: 1.0-Beta
paths:
  /ping:
    get:
      consumes:
      - '*/*'
      description: Ping the status of server, should be respond fastly.
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Show the status of server.
      tags:
      - Default
  /v1/authorization/b2b:
    post:
      consumes:
      - application/json
      description: API to authorize B2B officer account
      parameters:
      - description: Client Channel
        enum:
        - EBIZKEZBEK
        - B2BCLIENT
        in: header
        name: x-client-channel
        required: true
        type: string
      - default: android 10
        description: Client OS or Browser Agent
        in: header
        name: x-client-os
        required: true
        type: string
      - description: Client Device ID
        in: header
        name: x-client-device
        required: true
        type: string
      - default: 1.0.0
        description: Client Platform Version
        in: header
        name: x-client-version
        required: true
        type: string
      - description: Client Original Timestamp in UNIX format (EPOCH)
        in: header
        name: x-client-timestamp
        type: string
      - description: B2B Officer Authentication Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.OfficerAuthenticationRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: API B2B Authorization
      tags:
      - Authorization APIs
  /v1/authorization/client:
    post:
      consumes:
      - application/json
      description: API to authorize client's signature and code
      parameters:
      - description: Client signature using HMAC SHA256, signature formula is <b>HEX(HMAC(SHA256(UPPER(HTTP-METHOD):UPPER(CODE):UNIX-EPOCH:UPPER(API-KEY))))</b>
        in: header
        name: x-client-signature
        required: true
        type: string
      - description: Client API Key
        in: header
        name: x-api-key
        required: true
        type: string
      - description: Client Channel
        enum:
        - EBIZKEZBEK
        - B2BCLIENT
        in: header
        name: x-client-channel
        required: true
        type: string
      - default: android 10
        description: Client OS or Browser Agent
        in: header
        name: x-client-os
        required: true
        type: string
      - description: Client Device ID
        in: header
        name: x-client-device
        required: true
        type: string
      - default: 1.0.0
        description: Client Platform Version
        in: header
        name: x-client-version
        required: true
        type: string
      - description: Client Original Timestamp in UNIX format (EPOCH)
        in: header
        name: x-client-timestamp
        required: true
        type: string
      - description: Client Authentication Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.ClientAuthenticationRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: API Client Authorization
      tags:
      - Authorization APIs
  /v1/authorization/otp:
    post:
      consumes:
      - application/json
      description: API to validate B2B officer account OTP
      parameters:
      - description: Client Channel
        enum:
        - EBIZKEZBEK
        - B2BCLIENT
        in: header
        name: x-client-channel
        required: true
        type: string
      - default: android 10
        description: Client OS or Browser Agent
        in: header
        name: x-client-os
        required: true
        type: string
      - description: Client Device ID
        in: header
        name: x-client-device
        required: true
        type: string
      - default: 1.0.0
        description: Client Platform Version
        in: header
        name: x-client-version
        required: true
        type: string
      - description: Client Original Timestamp in UNIX format (EPOCH)
        in: header
        name: x-client-timestamp
        type: string
      - description: Client Transaction ID
        in: header
        name: x-client-trxid
        required: true
        type: string
      - description: B2B Officer Authentication Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.OfficerValidationRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: API B2B OTP Validation
      tags:
      - Authorization APIs
  /v1/cashbacks:
    post:
      consumes:
      - application/json
      description: API to apply cashback on client's transaction
      parameters:
      - default: Bearer
        description: Your Token to Access
        in: header
        name: Authorization
        type: string
      - description: Client Channel
        enum:
        - EBIZKEZBEK
        - B2BCLIENT
        in: header
        name: x-client-channel
        required: true
        type: string
      - default: android 10
        description: Client OS or Browser Agent
        in: header
        name: x-client-os
        required: true
        type: string
      - description: Client Device ID
        in: header
        name: x-client-device
        required: true
        type: string
      - default: 1.0.0
        description: Client Platform Version
        in: header
        name: x-client-version
        required: true
        type: string
      - description: Client Original Timestamp in UNIX format (EPOCH)
        in: header
        name: x-client-timestamp
        type: string
      - description: Transaction Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.TransactionRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: API Apply Cashback
      tags:
      - Client Cashback APIs
  /v1/cashbacks/{trxId}:
    post:
      consumes:
      - application/json
      description: API to view detail of applied cashback based on the given Kezbek
        transaction reference
      parameters:
      - default: Bearer
        description: Your Token to Access
        in: header
        name: Authorization
        type: string
      - description: Client Channel
        enum:
        - EBIZKEZBEK
        - B2BCLIENT
        in: header
        name: x-client-channel
        required: true
        type: string
      - default: android 10
        description: Client OS or Browser Agent
        in: header
        name: x-client-os
        required: true
        type: string
      - description: Client Device ID
        in: header
        name: x-client-device
        required: true
        type: string
      - default: 1.0.0
        description: Client Platform Version
        in: header
        name: x-client-version
        required: true
        type: string
      - description: Client Original Timestamp in UNIX format (EPOCH)
        in: header
        name: x-client-timestamp
        type: string
      - description: Kezbek Transaction Reference
        in: path
        name: trxId
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: API Detail Applied Cashback
      tags:
      - Client Cashback APIs
  /v1/partners:
    post:
      consumes:
      - application/json
      description: API to register a new B2B Partner data as user and client
      parameters:
      - default: Bearer
        description: Your Token to Access
        in: header
        name: Authorization
        type: string
      - description: Client Channel
        enum:
        - EBIZKEZBEK
        - B2BCLIENT
        in: header
        name: x-client-channel
        required: true
        type: string
      - default: android 10
        description: Client OS or Browser Agent
        in: header
        name: x-client-os
        required: true
        type: string
      - description: Client Device ID
        in: header
        name: x-client-device
        required: true
        type: string
      - default: 1.0.0
        description: Client Platform Version
        in: header
        name: x-client-version
        required: true
        type: string
      - description: Client Original Timestamp in UNIX format (EPOCH)
        in: header
        name: x-client-timestamp
        type: string
      - default: PT. Lajada Piranti Commerce
        description: Partner Corporate
        in: formData
        name: partner
        required: true
        type: string
      - default: LAJADA
        description: Partner Code
        in: formData
        name: code
        required: true
        type: string
      - default: kezbek.support@lajada.net
        description: Partner Email
        in: formData
        name: email
        required: true
        type: string
      - default: "628123456789"
        description: MSISDN
        in: formData
        name: msisdn
        required: true
        type: string
      - default: John Doe
        description: Partner Officer
        in: formData
        name: officer
        required: true
        type: string
      - default: Bintaro Exchange Mall Blok A1
        description: Office Address
        in: formData
        name: address
        required: true
        type: string
      - description: Logo
        in: formData
        name: logo
        required: true
        type: file
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: API Add Partner
      tags:
      - Partner Management APIs
swagger: "2.0"
