basePath: /api
info:
  contact:
    email: developer@kezbek.id
    name: Kezbek Developer
    url: https://kezbek.id
  description: This trip service sandbox is used for testing purpose only. Serve Kezbek
    APIs for the customer. It is not intended for production use.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Kezbek - Cezbek Engine Sandbox
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - '*/*'
      description: Ping the status of server, should be respond fastly.
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Show the status of server.
      tags:
      - Default
  /v1/partners:
    post:
      consumes:
      - application/json
      parameters:
      - default: Bearer
        description: Your Token to Access
        in: header
        name: Authorization
        type: string
      - description: Client Channel
        enum:
        - EBIZKEZBEK
        in: header
        name: x-client-channel
        required: true
        type: string
      - default: android 10
        description: Client OS or Browser Agent
        in: header
        name: x-client-os
        required: true
        type: string
      - description: Client Device ID
        in: header
        name: x-client-device
        required: true
        type: string
      - default: 1.0.0
        description: Client Platform Version
        in: header
        name: x-client-version
        required: true
        type: string
      - description: Client Original Time Request in UNIX Timestamp
        in: header
        name: x-client-timestamp
        type: string
      - default: PT. Lajada Piranti Commerce
        description: Partner Corporate
        in: formData
        name: partner
        required: true
        type: string
      - default: LAJADA
        description: Partner Code
        in: formData
        name: code
        required: true
        type: string
      - default: kezbek.support@lajada.net
        description: Partner Email
        in: formData
        name: email
        required: true
        type: string
      - default: "628123456789"
        description: MSISDN
        in: formData
        name: msisdn
        required: true
        type: string
      - default: John Doe
        description: Partner Officer
        in: formData
        name: officer
        required: true
        type: string
      - default: "100000"
        description: Office Address
        in: formData
        name: address
        required: true
        type: string
      - description: Logo
        in: formData
        name: logo
        required: true
        type: file
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: Add Partner API
      tags:
      - Partner Management APIs
swagger: "2.0"
