name: cezbek-engine-ci-job-prod

on:
  push:
    tags:
      - api-v*

jobs:
  release:
    needs: delivery
    name: Release Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Auth AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-3

      - name: Auth to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Rolling Image API Production
        run: 'Rolling api image production...'