name: cezbek-engine-cicd-dev

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  delivery:
    name: Package Service
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Auth Amazon AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-3

      - name: Auth to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Package Job Service to Amazon ECR
        id: build-image-job
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_CEZBEK_JOB }}
          CONSUL_HOST: ${{ secrets.CONSUL_HOST }}
          CONSUL_PORT: ${{ secrets.CONSUL_PORT }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -f deployment/Dockerfile.job -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  --build-arg CONSUL_HOST=$CONSUL_HOST --build-arg CONSUL_PORT=$CONSUL_PORT --build-arg APP_CEZBEK_JOB=cezbek-job-dev .
          echo "Pushing cezbek job image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Pull Job Development
        uses: fifsky/ssh-action@master
        with:
          command: |
            ./login.sh && docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_CEZBEK_JOB }}:${{ env.IMAGE_TAG }}
          host: ${{secrets.EC2_DEV_HOSTNAME}}
          user: ${{secrets.EC2_DEV_USERNAME}}
          key: ${{secrets.EC2_DEV_PEM}}
          port: 22
          args: "-tt"

      - name: Package API Service to Amazon ECR
        id: build-image-api
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_CEZBEK_API }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          CONSUL_HOST: ${{ secrets.CONSUL_HOST }}
          CONSUL_PORT: ${{ secrets.CONSUL_PORT }}
        run: |
          docker build -f deployment/Dockerfile.api -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  --build-arg CONSUL_HOST=$CONSUL_HOST --build-arg CONSUL_PORT=$CONSUL_PORT --build-arg APP_CEZBEK_JOB=cezbek-api-dev .
          echo "Pushing cezbek api image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"