name: cezbek-engine-cicd-dev

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  release:
    name: Release Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull Job Development
        env:
          PRIVATE_KEY: ${{ secrets.EC2_DEV_PEM  }}
          HOSTNAME: ${{ secrets.EC2_DEV_HOSTNAME  }}
          USER_NAME: ${{ secrets.EC2_DEV_USERNAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            aws ecr get-login-password --region ap-southeast-3 | docker login --username AWS --password-stdin 735185491450.dkr.ecr.ap-southeast-3.amazonaws.com && docker pull 735185491450.dkr.ecr.ap-southeast-3.amazonaws.com/cezbek-job:latest && docker pull 735185491450.dkr.ecr.ap-southeast-3.amazonaws.com/cezbek-api:latest 
          '