name: cezbek-engine-cicd-dev

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  delivery:
    name: Package Service
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Auth Amazon AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-3

      - name: Auth to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Package Job Service to Amazon ECR
        id: build-image-job
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_CEZBEK_JOB }}
          CONSUL_HOST: ${{ secrets.CONSUL_HOST }}
          CONSUL_PORT: ${{ secrets.CONSUL_PORT }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -f deployment/Dockerfile.job -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  --build-arg CONSUL_HOST=$CONSUL_HOST --build-arg CONSUL_PORT=$CONSUL_PORT --build-arg APP_CEZBEK_JOB=cezbek-job-dev .
          echo "Pushing cezbek job image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" 

      - name: Package API Service to Amazon ECR
        id: build-image-api
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_CEZBEK_API }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          CONSUL_HOST: ${{ secrets.CONSUL_HOST }}
          CONSUL_PORT: ${{ secrets.CONSUL_PORT }}
        run: |
          docker build -f deployment/Dockerfile.api -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  --build-arg CONSUL_HOST=$CONSUL_HOST --build-arg CONSUL_PORT=$CONSUL_PORT --build-arg APP_CEZBEK_JOB=cezbek-api-dev .
          echo "Pushing cezbek api image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
  release:
    name: Release Package
    needs: delivery
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2
      - name: Pull Job Development
        env:
          PRIVATE_KEY: ${{ secrets.EC2_DEV_PEM  }}
          HOSTNAME: ${{ secrets.EC2_DEV_HOSTNAME  }}
          USER_NAME: ${{ secrets.EC2_DEV_USERNAME  }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            aws ecr get-login-password --region ap-southeast-3 | docker login --username AWS --password-stdin 735185491450.dkr.ecr.ap-southeast-3.amazonaws.com && docker pull 735185491450.dkr.ecr.ap-southeast-3.amazonaws.com/cezbek-job:${IMAGE_TAG} && docker pull 735185491450.dkr.ecr.ap-southeast-3.amazonaws.com/cezbek-api:{$IMAGE_TAG} 
          '